### PR TITLE
Fix default-type bucket isActive logic

### LINKED ISSUE #11: Buckets in the Default type show up as 'Inactive'
Currently, buckets that are in the Default bucket type show up as 'Inactive' on the Bucket view (see screenshot). (Buckets of other types work correctly, however).

(Jira issue REX-93)

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
- Fix `quorumRelevant` function and display code
- Fix default-type bucket isActive logic

Closes #11.

### CODE REVIEW

File: app/pods/bucket/model.js [hunk 1]
```diff
@@ -104,6 +104,11 @@ var Bucket = DS.Model.extend({
      * @type Boolean
      */
     isActive: function() {
+        if(this.get('bucketTypeId') === 'default') {
+            // Buckets in the Default type don't have the 'active' attribute
+            // in the props, but are actually active.
+            return true;
+        }
```
Comment (paultannenbaum) [inline app/pods/bucket/model.js:111]: What happens if the default bucket type is inactive? Is this possible or is a default bucket type always active?

**Comment by dmitrizagidulin** [comment]
@paultannenbaum - The default bucket type cannot be inactive.
This whole thing is due to the fact that back before Riak 2.0, there weren't bucket types that had to be activated, and so there was no notion of active/inactive.
But in 2.0, buckets in user-activated bucket types now inherited the `active` property.
Except for buckets in the `default` type. Now, Default never gets activated. It's there basically for backwards-compatibility. And because of that, buckets in the Default type do not have an `active` property.

**Comment by paultannenbaum** [comment]
:+1: looks good to me! Thanks for clarifying
